language: cpp
sudo:     false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-format-5.0
      - clang-5.0
      - g++-7
      - lcov

cache:
  directories: ["$HOME/cmakeTar", "$HOME/glslang"]

matrix:
  include:
    - os: linux
      compiler: gcc
      env: C_CXX='g++-7' C_CC="gcc-7" COVERAGE=ON

    - os: linux
      compiler: clang
      env: C_CXX='clang++-5.0' C_CC="clang-5.0" COVERAGE=OFF

before_install:
  - CM_V_MAJOR=3
  - CM_V_MINOR=10
  - CM_V_PATCH=1
  - CMAKE_BASE_NAME="cmake-${CM_V_MAJOR}.${CM_V_MINOR}.${CM_V_PATCH}-Linux-x86_64"
  - CMAKE_DOWNLOAD_LINK="https://cmake.org/files/v${CM_V_MAJOR}.${CM_V_MINOR}/${CMAKE_BASE_NAME}.tar.gz"
  - export CXX=$C_CXX
  - export CC=$CC
  - cd "$HOME"
  - mkdir "install"

  # init cache
  - if [ ! -d "cmakeTar"     ]; then mkdir "cmakeTar";                                                          fi
  - if [ ! -e "glslang/.git" ]; then rm -rf "glslang"; git clone "https://github.com/KhronosGroup/glslang.git"; fi

  # CMake
  - cd "$HOME/cmakeTar"
  - if [ ! -e "${CMAKE_BASE_NAME}.tar.gz" ]; then wget "$CMAKE_DOWNLOAD_LINK"; fi

  # glslang
  - cd "$HOME/glslang"
  - if [ ! -d build ]; then mkdir build; fi

install:
  # install CMake
  - cd "$HOME/cmakeTar"
  - tar -xf "${CMAKE_BASE_NAME}.tar.gz" -C "$HOME"
  - CMAKE_EXE="$HOME/${CMAKE_BASE_NAME}/bin/cmake"

  # install glslang
  - cd "$HOME/glslang/build"
  - git pull
  - ${CMAKE_EXE} -DCMAKE_CXX_COMPILER="g++" -DCMAKE_C_COMPILER="gcc" -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make install

  - if [[ "$COVERAGE" == "ON" ]]; then gem install coveralls-lcov; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - CLANG_FORMAT_CMD=clang-format-5.0 ./checkFormat.sh --only-check
  - mkdir build
  - cd build
  - ${CMAKE_EXE} -DCMAKE_INSTALL_PREFIX="$HOME/install" -DENABLE_CODE_COVERAGE=$COVERAGE ..
  - make
  - ./bin/tests

after_success:
  - if [[ "$COVERAGE" == "ON" ]]; then lcov --directory . --capture --output-file coverage.info;                      fi
  - if [[ "$COVERAGE" == "ON" ]]; then lcov --remove coverage.info "/usr/*" "*/external/*" "*/Enum2Str*" "*/test/*" "$HOME/install/*" "*BinaryOpParser*" "*SPIRVOperands*" "*ToolMagicNumber*" --output-file coverage.info; fi
  - if [[ "$COVERAGE" == "ON" ]]; then lcov --list coverage.info;                                                     fi
  - if [[ "$COVERAGE" == "ON" ]]; then coveralls-lcov --source-encoding=ISO-8859-1 coverage.info;                     fi
