/*
 * Copyright (C) 2017 Daniel Mensinger
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*!
 * \note This is an automatically generated file
 * \warning All changes to this file will be lost
 * Generated with ./lib/disassembler/default/generateParsers.sh
 *
 * SPIRV version: 1.2.2
 */

#pragma once

#include "spvCfg.hpp"
#include "SPIRVDisassembly.hpp"

namespace spirvPacker {
namespace dis {

typedef std::vector<uint32_t>::iterator ITER;


bool parseInstruction(dis::Instruction &_inst);

// Instructions
bool parse_OpNop(dis::Instruction &_inst);
bool parse_OpUndef(dis::Instruction &_inst);
bool parse_OpSourceContinued(dis::Instruction &_inst);
bool parse_OpSource(dis::Instruction &_inst);
bool parse_OpSourceExtension(dis::Instruction &_inst);
bool parse_OpName(dis::Instruction &_inst);
bool parse_OpMemberName(dis::Instruction &_inst);
bool parse_OpString(dis::Instruction &_inst);
bool parse_OpLine(dis::Instruction &_inst);
bool parse_OpExtension(dis::Instruction &_inst);
bool parse_OpExtInstImport(dis::Instruction &_inst);
bool parse_OpExtInst(dis::Instruction &_inst);
bool parse_OpMemoryModel(dis::Instruction &_inst);
bool parse_OpEntryPoint(dis::Instruction &_inst);
bool parse_OpExecutionMode(dis::Instruction &_inst);
bool parse_OpCapability(dis::Instruction &_inst);
bool parse_OpTypeVoid(dis::Instruction &_inst);
bool parse_OpTypeBool(dis::Instruction &_inst);
bool parse_OpTypeInt(dis::Instruction &_inst);
bool parse_OpTypeFloat(dis::Instruction &_inst);
bool parse_OpTypeVector(dis::Instruction &_inst);
bool parse_OpTypeMatrix(dis::Instruction &_inst);
bool parse_OpTypeImage(dis::Instruction &_inst);
bool parse_OpTypeSampler(dis::Instruction &_inst);
bool parse_OpTypeSampledImage(dis::Instruction &_inst);
bool parse_OpTypeArray(dis::Instruction &_inst);
bool parse_OpTypeRuntimeArray(dis::Instruction &_inst);
bool parse_OpTypeStruct(dis::Instruction &_inst);
bool parse_OpTypeOpaque(dis::Instruction &_inst);
bool parse_OpTypePointer(dis::Instruction &_inst);
bool parse_OpTypeFunction(dis::Instruction &_inst);
bool parse_OpTypeEvent(dis::Instruction &_inst);
bool parse_OpTypeDeviceEvent(dis::Instruction &_inst);
bool parse_OpTypeReserveId(dis::Instruction &_inst);
bool parse_OpTypeQueue(dis::Instruction &_inst);
bool parse_OpTypePipe(dis::Instruction &_inst);
bool parse_OpTypeForwardPointer(dis::Instruction &_inst);
bool parse_OpConstantTrue(dis::Instruction &_inst);
bool parse_OpConstantFalse(dis::Instruction &_inst);
bool parse_OpConstant(dis::Instruction &_inst);
bool parse_OpConstantComposite(dis::Instruction &_inst);
bool parse_OpConstantSampler(dis::Instruction &_inst);
bool parse_OpConstantNull(dis::Instruction &_inst);
bool parse_OpSpecConstantTrue(dis::Instruction &_inst);
bool parse_OpSpecConstantFalse(dis::Instruction &_inst);
bool parse_OpSpecConstant(dis::Instruction &_inst);
bool parse_OpSpecConstantComposite(dis::Instruction &_inst);
bool parse_OpSpecConstantOp(dis::Instruction &_inst);
bool parse_OpFunction(dis::Instruction &_inst);
bool parse_OpFunctionParameter(dis::Instruction &_inst);
bool parse_OpFunctionEnd(dis::Instruction &_inst);
bool parse_OpFunctionCall(dis::Instruction &_inst);
bool parse_OpVariable(dis::Instruction &_inst);
bool parse_OpImageTexelPointer(dis::Instruction &_inst);
bool parse_OpLoad(dis::Instruction &_inst);
bool parse_OpStore(dis::Instruction &_inst);
bool parse_OpCopyMemory(dis::Instruction &_inst);
bool parse_OpCopyMemorySized(dis::Instruction &_inst);
bool parse_OpAccessChain(dis::Instruction &_inst);
bool parse_OpInBoundsAccessChain(dis::Instruction &_inst);
bool parse_OpPtrAccessChain(dis::Instruction &_inst);
bool parse_OpArrayLength(dis::Instruction &_inst);
bool parse_OpGenericPtrMemSemantics(dis::Instruction &_inst);
bool parse_OpInBoundsPtrAccessChain(dis::Instruction &_inst);
bool parse_OpDecorate(dis::Instruction &_inst);
bool parse_OpMemberDecorate(dis::Instruction &_inst);
bool parse_OpDecorationGroup(dis::Instruction &_inst);
bool parse_OpGroupDecorate(dis::Instruction &_inst);
bool parse_OpGroupMemberDecorate(dis::Instruction &_inst);
bool parse_OpVectorExtractDynamic(dis::Instruction &_inst);
bool parse_OpVectorInsertDynamic(dis::Instruction &_inst);
bool parse_OpVectorShuffle(dis::Instruction &_inst);
bool parse_OpCompositeConstruct(dis::Instruction &_inst);
bool parse_OpCompositeExtract(dis::Instruction &_inst);
bool parse_OpCompositeInsert(dis::Instruction &_inst);
bool parse_OpCopyObject(dis::Instruction &_inst);
bool parse_OpTranspose(dis::Instruction &_inst);
bool parse_OpSampledImage(dis::Instruction &_inst);
bool parse_OpImageSampleImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleDrefImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleDrefExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleProjImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleProjExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleProjDrefImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSampleProjDrefExplicitLod(dis::Instruction &_inst);
bool parse_OpImageFetch(dis::Instruction &_inst);
bool parse_OpImageGather(dis::Instruction &_inst);
bool parse_OpImageDrefGather(dis::Instruction &_inst);
bool parse_OpImageRead(dis::Instruction &_inst);
bool parse_OpImageWrite(dis::Instruction &_inst);
bool parse_OpImage(dis::Instruction &_inst);
bool parse_OpImageQueryFormat(dis::Instruction &_inst);
bool parse_OpImageQueryOrder(dis::Instruction &_inst);
bool parse_OpImageQuerySizeLod(dis::Instruction &_inst);
bool parse_OpImageQuerySize(dis::Instruction &_inst);
bool parse_OpImageQueryLod(dis::Instruction &_inst);
bool parse_OpImageQueryLevels(dis::Instruction &_inst);
bool parse_OpImageQuerySamples(dis::Instruction &_inst);
bool parse_OpConvertFToU(dis::Instruction &_inst);
bool parse_OpConvertFToS(dis::Instruction &_inst);
bool parse_OpConvertSToF(dis::Instruction &_inst);
bool parse_OpConvertUToF(dis::Instruction &_inst);
bool parse_OpUConvert(dis::Instruction &_inst);
bool parse_OpSConvert(dis::Instruction &_inst);
bool parse_OpFConvert(dis::Instruction &_inst);
bool parse_OpQuantizeToF16(dis::Instruction &_inst);
bool parse_OpConvertPtrToU(dis::Instruction &_inst);
bool parse_OpSatConvertSToU(dis::Instruction &_inst);
bool parse_OpSatConvertUToS(dis::Instruction &_inst);
bool parse_OpConvertUToPtr(dis::Instruction &_inst);
bool parse_OpPtrCastToGeneric(dis::Instruction &_inst);
bool parse_OpGenericCastToPtr(dis::Instruction &_inst);
bool parse_OpGenericCastToPtrExplicit(dis::Instruction &_inst);
bool parse_OpBitcast(dis::Instruction &_inst);
bool parse_OpSNegate(dis::Instruction &_inst);
bool parse_OpFNegate(dis::Instruction &_inst);
bool parse_OpIAdd(dis::Instruction &_inst);
bool parse_OpFAdd(dis::Instruction &_inst);
bool parse_OpISub(dis::Instruction &_inst);
bool parse_OpFSub(dis::Instruction &_inst);
bool parse_OpIMul(dis::Instruction &_inst);
bool parse_OpFMul(dis::Instruction &_inst);
bool parse_OpUDiv(dis::Instruction &_inst);
bool parse_OpSDiv(dis::Instruction &_inst);
bool parse_OpFDiv(dis::Instruction &_inst);
bool parse_OpUMod(dis::Instruction &_inst);
bool parse_OpSRem(dis::Instruction &_inst);
bool parse_OpSMod(dis::Instruction &_inst);
bool parse_OpFRem(dis::Instruction &_inst);
bool parse_OpFMod(dis::Instruction &_inst);
bool parse_OpVectorTimesScalar(dis::Instruction &_inst);
bool parse_OpMatrixTimesScalar(dis::Instruction &_inst);
bool parse_OpVectorTimesMatrix(dis::Instruction &_inst);
bool parse_OpMatrixTimesVector(dis::Instruction &_inst);
bool parse_OpMatrixTimesMatrix(dis::Instruction &_inst);
bool parse_OpOuterProduct(dis::Instruction &_inst);
bool parse_OpDot(dis::Instruction &_inst);
bool parse_OpIAddCarry(dis::Instruction &_inst);
bool parse_OpISubBorrow(dis::Instruction &_inst);
bool parse_OpUMulExtended(dis::Instruction &_inst);
bool parse_OpSMulExtended(dis::Instruction &_inst);
bool parse_OpAny(dis::Instruction &_inst);
bool parse_OpAll(dis::Instruction &_inst);
bool parse_OpIsNan(dis::Instruction &_inst);
bool parse_OpIsInf(dis::Instruction &_inst);
bool parse_OpIsFinite(dis::Instruction &_inst);
bool parse_OpIsNormal(dis::Instruction &_inst);
bool parse_OpSignBitSet(dis::Instruction &_inst);
bool parse_OpLessOrGreater(dis::Instruction &_inst);
bool parse_OpOrdered(dis::Instruction &_inst);
bool parse_OpUnordered(dis::Instruction &_inst);
bool parse_OpLogicalEqual(dis::Instruction &_inst);
bool parse_OpLogicalNotEqual(dis::Instruction &_inst);
bool parse_OpLogicalOr(dis::Instruction &_inst);
bool parse_OpLogicalAnd(dis::Instruction &_inst);
bool parse_OpLogicalNot(dis::Instruction &_inst);
bool parse_OpSelect(dis::Instruction &_inst);
bool parse_OpIEqual(dis::Instruction &_inst);
bool parse_OpINotEqual(dis::Instruction &_inst);
bool parse_OpUGreaterThan(dis::Instruction &_inst);
bool parse_OpSGreaterThan(dis::Instruction &_inst);
bool parse_OpUGreaterThanEqual(dis::Instruction &_inst);
bool parse_OpSGreaterThanEqual(dis::Instruction &_inst);
bool parse_OpULessThan(dis::Instruction &_inst);
bool parse_OpSLessThan(dis::Instruction &_inst);
bool parse_OpULessThanEqual(dis::Instruction &_inst);
bool parse_OpSLessThanEqual(dis::Instruction &_inst);
bool parse_OpFOrdEqual(dis::Instruction &_inst);
bool parse_OpFUnordEqual(dis::Instruction &_inst);
bool parse_OpFOrdNotEqual(dis::Instruction &_inst);
bool parse_OpFUnordNotEqual(dis::Instruction &_inst);
bool parse_OpFOrdLessThan(dis::Instruction &_inst);
bool parse_OpFUnordLessThan(dis::Instruction &_inst);
bool parse_OpFOrdGreaterThan(dis::Instruction &_inst);
bool parse_OpFUnordGreaterThan(dis::Instruction &_inst);
bool parse_OpFOrdLessThanEqual(dis::Instruction &_inst);
bool parse_OpFUnordLessThanEqual(dis::Instruction &_inst);
bool parse_OpFOrdGreaterThanEqual(dis::Instruction &_inst);
bool parse_OpFUnordGreaterThanEqual(dis::Instruction &_inst);
bool parse_OpShiftRightLogical(dis::Instruction &_inst);
bool parse_OpShiftRightArithmetic(dis::Instruction &_inst);
bool parse_OpShiftLeftLogical(dis::Instruction &_inst);
bool parse_OpBitwiseOr(dis::Instruction &_inst);
bool parse_OpBitwiseXor(dis::Instruction &_inst);
bool parse_OpBitwiseAnd(dis::Instruction &_inst);
bool parse_OpNot(dis::Instruction &_inst);
bool parse_OpBitFieldInsert(dis::Instruction &_inst);
bool parse_OpBitFieldSExtract(dis::Instruction &_inst);
bool parse_OpBitFieldUExtract(dis::Instruction &_inst);
bool parse_OpBitReverse(dis::Instruction &_inst);
bool parse_OpBitCount(dis::Instruction &_inst);
bool parse_OpDPdx(dis::Instruction &_inst);
bool parse_OpDPdy(dis::Instruction &_inst);
bool parse_OpFwidth(dis::Instruction &_inst);
bool parse_OpDPdxFine(dis::Instruction &_inst);
bool parse_OpDPdyFine(dis::Instruction &_inst);
bool parse_OpFwidthFine(dis::Instruction &_inst);
bool parse_OpDPdxCoarse(dis::Instruction &_inst);
bool parse_OpDPdyCoarse(dis::Instruction &_inst);
bool parse_OpFwidthCoarse(dis::Instruction &_inst);
bool parse_OpEmitVertex(dis::Instruction &_inst);
bool parse_OpEndPrimitive(dis::Instruction &_inst);
bool parse_OpEmitStreamVertex(dis::Instruction &_inst);
bool parse_OpEndStreamPrimitive(dis::Instruction &_inst);
bool parse_OpControlBarrier(dis::Instruction &_inst);
bool parse_OpMemoryBarrier(dis::Instruction &_inst);
bool parse_OpAtomicLoad(dis::Instruction &_inst);
bool parse_OpAtomicStore(dis::Instruction &_inst);
bool parse_OpAtomicExchange(dis::Instruction &_inst);
bool parse_OpAtomicCompareExchange(dis::Instruction &_inst);
bool parse_OpAtomicCompareExchangeWeak(dis::Instruction &_inst);
bool parse_OpAtomicIIncrement(dis::Instruction &_inst);
bool parse_OpAtomicIDecrement(dis::Instruction &_inst);
bool parse_OpAtomicIAdd(dis::Instruction &_inst);
bool parse_OpAtomicISub(dis::Instruction &_inst);
bool parse_OpAtomicSMin(dis::Instruction &_inst);
bool parse_OpAtomicUMin(dis::Instruction &_inst);
bool parse_OpAtomicSMax(dis::Instruction &_inst);
bool parse_OpAtomicUMax(dis::Instruction &_inst);
bool parse_OpAtomicAnd(dis::Instruction &_inst);
bool parse_OpAtomicOr(dis::Instruction &_inst);
bool parse_OpAtomicXor(dis::Instruction &_inst);
bool parse_OpPhi(dis::Instruction &_inst);
bool parse_OpLoopMerge(dis::Instruction &_inst);
bool parse_OpSelectionMerge(dis::Instruction &_inst);
bool parse_OpLabel(dis::Instruction &_inst);
bool parse_OpBranch(dis::Instruction &_inst);
bool parse_OpBranchConditional(dis::Instruction &_inst);
bool parse_OpSwitch(dis::Instruction &_inst);
bool parse_OpKill(dis::Instruction &_inst);
bool parse_OpReturn(dis::Instruction &_inst);
bool parse_OpReturnValue(dis::Instruction &_inst);
bool parse_OpUnreachable(dis::Instruction &_inst);
bool parse_OpLifetimeStart(dis::Instruction &_inst);
bool parse_OpLifetimeStop(dis::Instruction &_inst);
bool parse_OpGroupAsyncCopy(dis::Instruction &_inst);
bool parse_OpGroupWaitEvents(dis::Instruction &_inst);
bool parse_OpGroupAll(dis::Instruction &_inst);
bool parse_OpGroupAny(dis::Instruction &_inst);
bool parse_OpGroupBroadcast(dis::Instruction &_inst);
bool parse_OpGroupIAdd(dis::Instruction &_inst);
bool parse_OpGroupFAdd(dis::Instruction &_inst);
bool parse_OpGroupFMin(dis::Instruction &_inst);
bool parse_OpGroupUMin(dis::Instruction &_inst);
bool parse_OpGroupSMin(dis::Instruction &_inst);
bool parse_OpGroupFMax(dis::Instruction &_inst);
bool parse_OpGroupUMax(dis::Instruction &_inst);
bool parse_OpGroupSMax(dis::Instruction &_inst);
bool parse_OpReadPipe(dis::Instruction &_inst);
bool parse_OpWritePipe(dis::Instruction &_inst);
bool parse_OpReservedReadPipe(dis::Instruction &_inst);
bool parse_OpReservedWritePipe(dis::Instruction &_inst);
bool parse_OpReserveReadPipePackets(dis::Instruction &_inst);
bool parse_OpReserveWritePipePackets(dis::Instruction &_inst);
bool parse_OpCommitReadPipe(dis::Instruction &_inst);
bool parse_OpCommitWritePipe(dis::Instruction &_inst);
bool parse_OpIsValidReserveId(dis::Instruction &_inst);
bool parse_OpGetNumPipePackets(dis::Instruction &_inst);
bool parse_OpGetMaxPipePackets(dis::Instruction &_inst);
bool parse_OpGroupReserveReadPipePackets(dis::Instruction &_inst);
bool parse_OpGroupReserveWritePipePackets(dis::Instruction &_inst);
bool parse_OpGroupCommitReadPipe(dis::Instruction &_inst);
bool parse_OpGroupCommitWritePipe(dis::Instruction &_inst);
bool parse_OpEnqueueMarker(dis::Instruction &_inst);
bool parse_OpEnqueueKernel(dis::Instruction &_inst);
bool parse_OpGetKernelNDrangeSubGroupCount(dis::Instruction &_inst);
bool parse_OpGetKernelNDrangeMaxSubGroupSize(dis::Instruction &_inst);
bool parse_OpGetKernelWorkGroupSize(dis::Instruction &_inst);
bool parse_OpGetKernelPreferredWorkGroupSizeMultiple(dis::Instruction &_inst);
bool parse_OpRetainEvent(dis::Instruction &_inst);
bool parse_OpReleaseEvent(dis::Instruction &_inst);
bool parse_OpCreateUserEvent(dis::Instruction &_inst);
bool parse_OpIsValidEvent(dis::Instruction &_inst);
bool parse_OpSetUserEventStatus(dis::Instruction &_inst);
bool parse_OpCaptureEventProfilingInfo(dis::Instruction &_inst);
bool parse_OpGetDefaultQueue(dis::Instruction &_inst);
bool parse_OpBuildNDRange(dis::Instruction &_inst);
bool parse_OpImageSparseSampleImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleDrefImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleDrefExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleProjImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleProjExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleProjDrefImplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseSampleProjDrefExplicitLod(dis::Instruction &_inst);
bool parse_OpImageSparseFetch(dis::Instruction &_inst);
bool parse_OpImageSparseGather(dis::Instruction &_inst);
bool parse_OpImageSparseDrefGather(dis::Instruction &_inst);
bool parse_OpImageSparseTexelsResident(dis::Instruction &_inst);
bool parse_OpNoLine(dis::Instruction &_inst);
bool parse_OpAtomicFlagTestAndSet(dis::Instruction &_inst);
bool parse_OpAtomicFlagClear(dis::Instruction &_inst);
bool parse_OpImageSparseRead(dis::Instruction &_inst);
bool parse_OpSizeOf(dis::Instruction &_inst);
bool parse_OpTypePipeStorage(dis::Instruction &_inst);
bool parse_OpConstantPipeStorage(dis::Instruction &_inst);
bool parse_OpCreatePipeFromPipeStorage(dis::Instruction &_inst);
bool parse_OpGetKernelLocalSizeForSubgroupCount(dis::Instruction &_inst);
bool parse_OpGetKernelMaxNumSubgroups(dis::Instruction &_inst);
bool parse_OpTypeNamedBarrier(dis::Instruction &_inst);
bool parse_OpNamedBarrierInitialize(dis::Instruction &_inst);
bool parse_OpMemoryNamedBarrier(dis::Instruction &_inst);
bool parse_OpModuleProcessed(dis::Instruction &_inst);
bool parse_OpExecutionModeId(dis::Instruction &_inst);
bool parse_OpDecorateId(dis::Instruction &_inst);
bool parse_OpSubgroupBallotKHR(dis::Instruction &_inst);
bool parse_OpSubgroupFirstInvocationKHR(dis::Instruction &_inst);
bool parse_OpSubgroupAllKHR(dis::Instruction &_inst);
bool parse_OpSubgroupAnyKHR(dis::Instruction &_inst);
bool parse_OpSubgroupAllEqualKHR(dis::Instruction &_inst);
bool parse_OpSubgroupReadInvocationKHR(dis::Instruction &_inst);
bool parse_OpGroupIAddNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupFAddNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupFMinNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupUMinNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupSMinNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupFMaxNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupUMaxNonUniformAMD(dis::Instruction &_inst);
bool parse_OpGroupSMaxNonUniformAMD(dis::Instruction &_inst);
bool parse_OpFragmentMaskFetchAMD(dis::Instruction &_inst);
bool parse_OpFragmentFetchAMD(dis::Instruction &_inst);
bool parse_OpSubgroupShuffleINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupShuffleDownINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupShuffleUpINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupShuffleXorINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupBlockReadINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupBlockWriteINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupImageBlockReadINTEL(dis::Instruction &_inst);
bool parse_OpSubgroupImageBlockWriteINTEL(dis::Instruction &_inst);

// Operands
ITER parse_ImageOperands(ImageOperands &_val, ITER _begin, ITER _end);
ITER parse_FPFastMathMode(FPFastMathMode &_val, ITER _begin, ITER _end);
ITER parse_SelectionControl(SelectionControl &_val, ITER _begin, ITER _end);
ITER parse_LoopControl(LoopControl &_val, ITER _begin, ITER _end);
ITER parse_FunctionControl(FunctionControl &_val, ITER _begin, ITER _end);
ITER parse_MemorySemantics(MemorySemantics &_val, ITER _begin, ITER _end);
ITER parse_MemoryAccess(MemoryAccess &_val, ITER _begin, ITER _end);
ITER parse_KernelProfilingInfo(KernelProfilingInfo &_val, ITER _begin, ITER _end);
ITER parse_SourceLanguage(SourceLanguage &_val, ITER _begin, ITER _end);
ITER parse_ExecutionModel(ExecutionModel &_val, ITER _begin, ITER _end);
ITER parse_AddressingModel(AddressingModel &_val, ITER _begin, ITER _end);
ITER parse_MemoryModel(MemoryModel &_val, ITER _begin, ITER _end);
ITER parse_ExecutionMode(ExecutionMode &_val, ITER _begin, ITER _end);
ITER parse_StorageClass(StorageClass &_val, ITER _begin, ITER _end);
ITER parse_Dim(Dim &_val, ITER _begin, ITER _end);
ITER parse_SamplerAddressingMode(SamplerAddressingMode &_val, ITER _begin, ITER _end);
ITER parse_SamplerFilterMode(SamplerFilterMode &_val, ITER _begin, ITER _end);
ITER parse_ImageFormat(ImageFormat &_val, ITER _begin, ITER _end);
ITER parse_ImageChannelOrder(ImageChannelOrder &_val, ITER _begin, ITER _end);
ITER parse_ImageChannelDataType(ImageChannelDataType &_val, ITER _begin, ITER _end);
ITER parse_FPRoundingMode(FPRoundingMode &_val, ITER _begin, ITER _end);
ITER parse_LinkageType(LinkageType &_val, ITER _begin, ITER _end);
ITER parse_AccessQualifier(AccessQualifier &_val, ITER _begin, ITER _end);
ITER parse_FunctionParameterAttribute(FunctionParameterAttribute &_val, ITER _begin, ITER _end);
ITER parse_Decoration(Decoration &_val, ITER _begin, ITER _end);
ITER parse_BuiltIn(BuiltIn &_val, ITER _begin, ITER _end);
ITER parse_Scope(Scope &_val, ITER _begin, ITER _end);
ITER parse_GroupOperation(GroupOperation &_val, ITER _begin, ITER _end);
ITER parse_KernelEnqueueFlags(KernelEnqueueFlags &_val, ITER _begin, ITER _end);
ITER parse_Capability(Capability &_val, ITER _begin, ITER _end);
ITER parse_IdResultType(IdResultType &_val, ITER _begin, ITER _end);
ITER parse_IdResult(IdResult &_val, ITER _begin, ITER _end);
ITER parse_IdMemorySemantics(IdMemorySemantics &_val, ITER _begin, ITER _end);
ITER parse_IdScope(IdScope &_val, ITER _begin, ITER _end);
ITER parse_IdRef(IdRef &_val, ITER _begin, ITER _end);
ITER parse_LiteralInteger(LiteralInteger &_val, ITER _begin, ITER _end);
ITER parse_LiteralString(LiteralString &_val, ITER _begin, ITER _end);
ITER parse_LiteralContextDependentNumber(LiteralContextDependentNumber &_val, ITER _begin, ITER _end);
ITER parse_LiteralExtInstInteger(LiteralExtInstInteger &_val, ITER _begin, ITER _end);
ITER parse_LiteralSpecConstantOpInteger(LiteralSpecConstantOpInteger &_val, ITER _begin, ITER _end);
ITER parse_PairLiteralIntegerIdRef(PairLiteralIntegerIdRef &_val, ITER _begin, ITER _end);
ITER parse_PairIdRefLiteralInteger(PairIdRefLiteralInteger &_val, ITER _begin, ITER _end);
ITER parse_PairIdRefIdRef(PairIdRefIdRef &_val, ITER _begin, ITER _end);

} // namespace dis
} // namespace spirvPacker
